export {
  // Metadata constants
  INTERNAL_METADATA_KEY,
  // Climate sub-schemas (typed replacements for UnknownRecord)
  ClimateBaselineBandsSchema,
  ClimateBaselineBlendSchema,
  ClimateBaselineOrographicSchema,
  ClimateBaselineCoastalSchema,
  ClimateBaselineNoiseSchema,
  ClimateRefineWaterGradientSchema,
  ClimateRefineOrographicSchema,
  ClimateRefineRiverCorridorSchema,
  ClimateRefineLowBasinSchema,
  ClimateStoryPaleoElevationCarvingSchema,
  ClimateStoryPaleoSchema,
  ClimateStoryPaleoSizeScalingSchema,
  // Main schemas
  BiomeConfigSchema,
  BiomeThresholdsSchema,
  NarrativePolicySchema,
  ClimateBaselineSchema,
  ClimateConfigSchema,
  ClimateRefineSchema,
  ContinentBoundsSchema,
  ContinentalMarginsConfigSchema,
  CoastlineBayConfigSchema,
  CoastlineFjordConfigSchema,
  CoastlinePlateBiasConfigSchema,
  CoastlinesConfigSchema,
  CorridorsConfigSchema,
  FeaturesConfigSchema,
  FeaturesDensityConfigSchema,
  FloodplainsConfigSchema,
  FoundationConfigSchema,
  FoundationDiagnosticsConfigSchema,
  FoundationDirectionalityConfigSchema,
  FoundationDynamicsConfigSchema,
  FoundationOceanSeparationConfigSchema,
  FoundationPlatesConfigSchema,
  FoundationPolicyConfigSchema,
  FoundationSeedConfigSchema,
  FoundationSurfaceConfigSchema,
  HotspotTunablesSchema,
  IslandHopCorridorConfigSchema,
  IslandsConfigSchema,
  LandCorridorConfigSchema,
  LandmassConfigSchema,
  LandmassGeometryPostSchema,
  LandmassGeometrySchema,
  LandmassTectonicsConfigSchema,
  MapGenConfigSchema,
  MountainsConfigSchema,
  OceanSeparationConfigSchema,
  OceanSeparationEdgePolicySchema,
  PlacementConfigSchema,
  RiverCorridorConfigSchema,
  SeaCorridorPolicySchema,
  StartsConfigSchema,
  OrogenyTunablesSchema,
  RiftTunablesSchema,
  StoryConfigSchema,
  VolcanoesConfigSchema,
} from "@mapgen/config/schema.js";

export type {
  // Climate sub-types (typed replacements for UnknownRecord)
  ClimateBaselineBands,
  ClimateBaselineBlend,
  ClimateBaselineOrographic,
  ClimateBaselineCoastal,
  ClimateBaselineNoise,
  ClimateRefineWaterGradient,
  ClimateRefineOrographic,
  ClimateRefineRiverCorridor,
  ClimateRefineLowBasin,
  ClimateStoryPaleo,
  ClimateStoryPaleoElevationCarving,
  ClimateStoryPaleoSizeScaling,
  // Main types
  BiomeConfig,
  BiomeThresholds,
  NarrativePolicy,
  ClimateBaseline,
  ClimateConfig,
  ClimateRefine,
  ContinentBoundsConfig,
  ContinentalMarginsConfig,
  CoastlineBayConfig,
  CoastlineFjordConfig,
  CoastlinePlateBiasConfig,
  CoastlinesConfig,
  CorridorsConfig,
  FeaturesConfig,
  FeaturesDensityConfig,
  FloodplainsConfig,
  FoundationConfig,
  FoundationDiagnosticsConfig,
  FoundationDirectionalityConfig,
  FoundationDynamicsConfig,
  FoundationOceanSeparationConfig,
  FoundationPlatesConfig,
  FoundationPolicyConfig,
  FoundationSeedConfig,
  FoundationSurfaceConfig,
  HotspotTunables,
  IslandHopCorridorConfig,
  IslandsConfig,
  LandCorridorConfig,
  LandmassConfig,
  LandmassGeometry,
  LandmassGeometryPost,
  LandmassTectonicsConfig,
  MapGenConfig,
  MountainsConfig,
  OceanSeparationConfig,
  OceanSeparationEdgePolicy,
  PlacementConfig,
  RiverCorridorConfig,
  SeaCorridorPolicy,
  StartsConfig,
  OrogenyTunables,
  RiftTunables,
  StoryConfig,
  VolcanoesConfig,
} from "@mapgen/config/schema.js";

export {
  parseConfig,
  safeParseConfig,
  getDefaultConfig,
  getJsonSchema,
  getPublicJsonSchema,
  type ParseResult,
} from "@mapgen/config/loader.js";
