var g_MountainTerrain = GameInfo.Terrains.find((t) => t.TerrainType == "TERRAIN_MOUNTAIN").$index;
var g_HillTerrain = GameInfo.Terrains.find((t) => t.TerrainType == "TERRAIN_HILL").$index;
var g_FlatTerrain = GameInfo.Terrains.find((t) => t.TerrainType == "TERRAIN_FLAT").$index;
var g_CoastTerrain = GameInfo.Terrains.find((t) => t.TerrainType == "TERRAIN_COAST").$index;
var g_OceanTerrain = GameInfo.Terrains.find((t) => t.TerrainType == "TERRAIN_OCEAN").$index;
var g_NavigableRiverTerrain = GameInfo.Terrains.find(
  (t) => t.TerrainType == "TERRAIN_NAVIGABLE_RIVER"
).$index;
var g_TundraBiome = GameInfo.Biomes.find((t) => t.BiomeType == "BIOME_TUNDRA").$index;
var g_GrasslandBiome = GameInfo.Biomes.find((t) => t.BiomeType == "BIOME_GRASSLAND").$index;
var g_PlainsBiome = GameInfo.Biomes.find((t) => t.BiomeType == "BIOME_PLAINS").$index;
var g_TropicalBiome = GameInfo.Biomes.find((t) => t.BiomeType == "BIOME_TROPICAL").$index;
var g_DesertBiome = GameInfo.Biomes.find((t) => t.BiomeType == "BIOME_DESERT").$index;
var g_MarineBiome = GameInfo.Biomes.find((t) => t.BiomeType == "BIOME_MARINE").$index;
var g_VolcanoFeature = GameInfo.Features.find((t) => t.FeatureType == "FEATURE_VOLCANO").$index;
let temp;
var g_GrasslandLatitude = 0;
var g_PlainsLatitude = 0;
var g_DesertLatitude = 0;
var g_TropicalLatitude = 0;
temp = GameInfo.Biomes.find((t) => t.BiomeType == "BIOME_GRASSLAND").MaxLatitude;
if (temp) g_GrasslandLatitude = temp;
temp = GameInfo.Biomes.find((t) => t.BiomeType == "BIOME_PLAINS").MaxLatitude;
if (temp) g_PlainsLatitude = temp;
temp = GameInfo.Biomes.find((t) => t.BiomeType == "BIOME_DESERT").MaxLatitude;
if (temp) g_DesertLatitude = temp;
temp = GameInfo.Biomes.find((t) => t.BiomeType == "BIOME_TROPICAL").MaxLatitude;
if (temp) g_TropicalLatitude = temp;
var g_LandmassFractal = 0;
var g_MountainFractal = 1;
var g_HillFractal = 2;
var g_PolarWaterRows = 2;
var g_OceanWaterColumns = 4;
var g_FractalWeight = 0.8;
var g_WaterPercent = 20;
var g_IgnoreStartSectorPctFromCtr = 93;
var g_StartSectorWeight = 0.5;
var g_CenterWeight = 0.7;
var g_CenterExponent = 1.5;
var g_Cutoff = 2;
var g_AvoidSeamOffset = 2;
var g_IslandWidth = 5;
var g_StandardRainfall = 100;
var g_MountainTopIncrease = 100;
var g_RainShadowDrop = -80;
var g_RainShadowIncreasePerHex = 10;
var g_RequiredBufferBetweenMajorStarts = 6;
var g_DesiredBufferBetweenMajorStarts = 12;
var g_RequiredDistanceFromMajorForDiscoveries = 3;

export { g_AvoidSeamOffset, g_CenterExponent, g_CenterWeight, g_CoastTerrain, g_Cutoff, g_DesertBiome, g_DesertLatitude, g_DesiredBufferBetweenMajorStarts, g_FlatTerrain, g_FractalWeight, g_GrasslandBiome, g_GrasslandLatitude, g_HillFractal, g_HillTerrain, g_IgnoreStartSectorPctFromCtr, g_IslandWidth, g_LandmassFractal, g_MarineBiome, g_MountainFractal, g_MountainTerrain, g_MountainTopIncrease, g_NavigableRiverTerrain, g_OceanTerrain, g_OceanWaterColumns, g_PlainsBiome, g_PlainsLatitude, g_PolarWaterRows, g_RainShadowDrop, g_RainShadowIncreasePerHex, g_RequiredBufferBetweenMajorStarts, g_RequiredDistanceFromMajorForDiscoveries, g_StandardRainfall, g_StartSectorWeight, g_TropicalBiome, g_TropicalLatitude, g_TundraBiome, g_VolcanoFeature, g_WaterPercent };
//# sourceMappingURL=map-globals.js.map
