export const COLLECTION = {
    ALL_CITIES: 'COLLECTION_ALL_CITIES',
    ALL_PLAYERS: 'COLLECTION_ALL_PLAYERS',
    ALL_UNITS: 'COLLECTION_ALL_UNITS',
    MAJOR_PLAYERS: 'COLLECTION_MAJOR_PLAYERS',
    OWNER: 'COLLECTION_OWNER',
    PLAYER_CAPITAL_CITY: 'COLLECTION_PLAYER_CAPITAL_CITY',
    PLAYER_CONSTRUCTIBLES: 'COLLECTION_PLAYER_CONSTRUCTIBLES',
    PLAYER_PLOT_YIELDS: 'COLLECTION_PLAYER_PLOT_YIELDS',
    PLAYER_UNITS: 'COLLECTION_PLAYER_UNITS',
    UNIT_COMBAT: 'COLLECTION_UNIT_COMBAT',
} as const;