export const KIND = {
    UNIT: 'KIND_UNIT',
    TRAIT: 'KIND_TRAIT',
    BUILDING: 'KIND_BUILDING',
    CIVILIZATION: 'KIND_CIVILIZATION',
    CONSTRUCTIBLE: 'KIND_CONSTRUCTIBLE',
    QUARTER: 'KIND_QUARTER',
    UNLOCK: 'KIND_UNLOCK',
    IMPROVEMENT: 'KIND_IMPROVEMENT',
} as const;
