export const TRAIT = {
    ANTIQUITY_CIV: "TRAIT_ANTIQUITY_CIV",
    ATTRIBUTE_CULTURAL: "TRAIT_ATTRIBUTE_CULTURAL",
    ATTRIBUTE_ECONOMIC: "TRAIT_ATTRIBUTE_ECONOMIC",
    ATTRIBUTE_SCIENTIFIC: "TRAIT_ATTRIBUTE_SCIENTIFIC",
    ATTRIBUTE_POLITICAL: "TRAIT_ATTRIBUTE_POLITICAL",
    ATTRIBUTE_EXPANSIONIST: "TRAIT_ATTRIBUTE_EXPANSIONIST",
    ATTRIBUTE_MILITARISTIC: "TRAIT_ATTRIBUTE_MILITARISTIC",
} as const;
