export const UNIT_CLASS = {
    RECON: 'UNIT_CLASS_RECON',
    RECON_ABILITIES: 'UNIT_CLASS_RECON_ABILITIES',
    INFLUENCE_INDEPENDENT: 'UNIT_CLASS_INFLUENCE_INDEPENDENT',
    MOUNTED: 'UNIT_CLASS_MOUNTED',
    CAVALRY: 'UNIT_CLASS_CAVALRY',
    RANGED: 'UNIT_CLASS_RANGED',
    PROSPECTOR: 'UNIT_CLASS_PROSPECTOR',
} as const;
