export {
  // Metadata constants
  INTERNAL_METADATA_KEY,
  // Climate sub-schemas (typed replacements for UnknownRecord)
  ClimateBaselineBandsSchema,
  ClimateBaselineBlendSchema,
  ClimateBaselineOrographicSchema,
  ClimateBaselineCoastalSchema,
  ClimateBaselineNoiseSchema,
  ClimateRefineWaterGradientSchema,
  ClimateRefineOrographicSchema,
  ClimateRefineRiverCorridorSchema,
  ClimateRefineLowBasinSchema,
  // Main schemas
  BiomeConfigSchema,
  ClimateBaselineSchema,
  ClimateConfigSchema,
  ClimateRefineSchema,
  ContinentBoundsSchema,
  CoastlineBayConfigSchema,
  CoastlineFjordConfigSchema,
  CoastlinePlateBiasConfigSchema,
  CoastlinesConfigSchema,
  CorridorsConfigSchema,
  DiagnosticsConfigSchema,
  FeaturesConfigSchema,
  FeaturesDensityConfigSchema,
  FloodplainsConfigSchema,
  FoundationConfigSchema,
  FoundationDiagnosticsConfigSchema,
  FoundationDirectionalityConfigSchema,
  FoundationDynamicsConfigSchema,
  FoundationOceanSeparationConfigSchema,
  FoundationPlatesConfigSchema,
  FoundationPolicyConfigSchema,
  FoundationSeedConfigSchema,
  FoundationSurfaceConfigSchema,
  HotspotTunablesSchema,
  IslandsConfigSchema,
  LandmassConfigSchema,
  LandmassGeometryPostSchema,
  LandmassGeometrySchema,
  LandmassTectonicsConfigSchema,
  MapGenConfigSchema,
  MountainsConfigSchema,
  OceanSeparationConfigSchema,
  OceanSeparationEdgePolicySchema,
  PlacementConfigSchema,
  SeaCorridorPolicySchema,
  StageConfigSchema,
  StageDescriptorSchema,
  StageManifestSchema,
  StartsConfigSchema,
  StoryConfigSchema,
  TogglesSchema,
  VolcanoesConfigSchema,
} from "./schema.js";

export type {
  // Climate sub-types (typed replacements for UnknownRecord)
  ClimateBaselineBands,
  ClimateBaselineBlend,
  ClimateBaselineOrographic,
  ClimateBaselineCoastal,
  ClimateBaselineNoise,
  ClimateRefineWaterGradient,
  ClimateRefineOrographic,
  ClimateRefineRiverCorridor,
  ClimateRefineLowBasin,
  // Main types
  BiomeConfig,
  ClimateBaseline,
  ClimateConfig,
  ClimateRefine,
  ContinentBoundsConfig,
  CoastlineBayConfig,
  CoastlineFjordConfig,
  CoastlinePlateBiasConfig,
  CoastlinesConfig,
  CorridorsConfig,
  DiagnosticsConfig,
  FeaturesConfig,
  FeaturesDensityConfig,
  FloodplainsConfig,
  FoundationConfig,
  FoundationDiagnosticsConfig,
  FoundationDirectionalityConfig,
  FoundationDynamicsConfig,
  FoundationOceanSeparationConfig,
  FoundationPlatesConfig,
  FoundationPolicyConfig,
  FoundationSeedConfig,
  FoundationSurfaceConfig,
  HotspotTunables,
  IslandsConfig,
  LandmassConfig,
  LandmassGeometry,
  LandmassGeometryPost,
  LandmassTectonicsConfig,
  MapGenConfig,
  MountainsConfig,
  OceanSeparationConfig,
  OceanSeparationEdgePolicy,
  PlacementConfig,
  SeaCorridorPolicy,
  StageConfig,
  StageDescriptor,
  StageManifest,
  StartsConfig,
  StoryConfig,
  Toggles,
  VolcanoesConfig,
} from "./schema.js";

export {
  parseConfig,
  safeParseConfig,
  getDefaultConfig,
  getJsonSchema,
  getPublicJsonSchema,
  type ParseResult,
} from "./loader.js";

export {
  applyPresets,
  getPresetConfig,
  type MapGenPresetName,
} from "./presets.js";
