import * as lodash from "lodash";
import * as fs from 'node:fs';

import { TClassProperties, TObjectValues } from "../types";
import { ACTION_GROUP_ACTION } from "../constants";

import { ActionGroup } from "./ActionGroup";
import { Base } from "./Base";
import { Civilization } from "./Civilization";
import { Constructible } from "./Constructible";
import { Unit } from "./Unit";
import { FileXml } from "./FileXml";
import { Icon } from "./Icon";

type TMod = TClassProperties<Mod>;

export class Mod extends Base<TMod> implements TMod {
    id: string = 'test';
    name: string = 'test'
    version: string | number = 1;
    description: string = 'generated by https://github.com/izica/civ7-modding-tool';
    authors: string = 'generated by https://github.com/izica/civ7-modding-tool';
    affectsSavedGames: boolean = true;

    civilizations: Civilization[] = [];
    constructibles: Constructible[] = [];
    units: Unit[] = [];

    constructor(payload: Partial<TMod> = {}) {
        super();
        this.fill(payload);
    }

    getFiles() {
        return [
            ...this.civilizations.flatMap(civilization => civilization.getFiles()),
            ...this.constructibles.flatMap(constructible => constructible.getFiles()),
            ...this.units.flatMap(unit => unit.getFiles()),
        ];
    }

    // TODO maybe refactoring in feature?
    build(dist = './dist', clear = false) {
        if (clear) {
            fs.mkdirSync(dist, { recursive: true });
            fs.rmSync(dist, { recursive: true });
            fs.mkdirSync(dist, { recursive: true });
        }

        const files = this.getFiles();

        const criterias = lodash.uniqBy(
            files.flatMap(file => file.actionGroups.map(actionGroup => actionGroup.criteria)),
            criteria => criteria.id
        );

        const actionGroups: Record<string, {
            actionGroup: ActionGroup,
            actions: Partial<Record<TObjectValues<typeof ACTION_GROUP_ACTION>, string[]>>
        }> = {};

        files.forEach(file => {
            file.actionGroups.forEach(actionGroup => {
                if(!actionGroups[actionGroup.id]) {
                    actionGroups[actionGroup.id] = { actionGroup, actions: {} }
                }

                file.actionGroupActions.forEach(actionGroupAction => {
                    if(!actionGroups[actionGroup.id].actions[actionGroupAction]) {
                        actionGroups[actionGroup.id].actions[actionGroupAction] = [];
                    }
                    actionGroups[actionGroup.id].actions[actionGroupAction].push(file.modInfoPath);
                })
            });
        });

        const modInfo = new FileXml({
            name: `${this.id}.modinfo`,
            path: '/',
            content: {
                _name: 'Mod',
                _attrs: {
                    id: this.id,
                    version: this.version,
                    xmlms: "ModInfo"
                },
                _content: {
                    Properties: {
                        Name: this.name,
                        Description: this.description,
                        Authors: this.authors,
                        Version: this.version,
                        AffectsSavedGames: +this.affectsSavedGames
                    },
                    // TODO dynamic deps?
                    Dependencies: [{
                        _name: 'Mod',
                        _attrs: {
                            id: 'base-standard',
                            title: 'LOC_MODULE_BASE_STANDARD_NAME'
                        }
                    }],
                    ActionCriteria: criterias.map(criteria => criteria.toXMLElement()),
                    ActionGroups: Object.values(actionGroups).map(({ actionGroup, actions }) => ({
                        _name: 'ActionGroup',
                        _attrs: {
                            id: actionGroup.id,
                            scope: actionGroup.scope,
                            criteria: actionGroup.criteria.id,
                        },
                        _content: {
                            Actions: Object.entries(actions).map(([key, items]) => ({
                                [key]: items.map(item => ({
                                    Item: item
                                }))
                            }))
                        }
                    }))
                }
            }
        });

        modInfo.write(dist);
        files.forEach(file => file.write(dist));

        return [];
    }
}