/**
 * Bootstrap Module Types
 *
 * Type definitions for configuration and bootstrap system.
 */

import type { ContinentBounds } from "@civ7/adapter";
import type {
  BiomeConfig,
  ClimateBaseline,
  ClimateConfig,
  ClimateRefine,
  CoastlineBayConfig,
  CoastlineFjordConfig,
  CoastlinePlateBiasConfig,
  CoastlinesConfig,
  CorridorsConfig,
  DiagnosticsConfig,
  FeaturesConfig,
  FeaturesDensityConfig,
  FloodplainsConfig,
  FoundationConfig,
  FoundationDiagnosticsConfig,
  FoundationDirectionalityConfig,
  FoundationDynamicsConfig,
  FoundationOceanSeparationConfig,
  FoundationPlatesConfig,
  FoundationPolicyConfig,
  FoundationSeedConfig,
  FoundationSurfaceConfig,
  HotspotTunables,
  IslandsConfig,
  LandmassConfig,
  LandmassGeometry,
  LandmassGeometryPost,
  LandmassTectonicsConfig,
  MapGenConfig,
  MountainsConfig,
  OceanSeparationConfig,
  OceanSeparationEdgePolicy,
  PlacementConfig,
  SeaCorridorPolicy,
  StageConfig,
  StageDescriptor,
  StageManifest,
  StartsConfig,
  StoryConfig,
  VolcanoesConfig,
} from "../config/index.js";

export type MapConfig = MapGenConfig;

export type {
  BiomeConfig,
  ClimateBaseline,
  ClimateConfig,
  ClimateRefine,
  CoastlineBayConfig,
  CoastlineFjordConfig,
  CoastlinePlateBiasConfig,
  CoastlinesConfig,
  CorridorsConfig,
  DiagnosticsConfig,
  FeaturesConfig,
  FeaturesDensityConfig,
  FloodplainsConfig,
  FoundationConfig,
  FoundationDiagnosticsConfig,
  FoundationDirectionalityConfig,
  FoundationDynamicsConfig,
  FoundationOceanSeparationConfig,
  FoundationPlatesConfig,
  FoundationPolicyConfig,
  FoundationSeedConfig,
  FoundationSurfaceConfig,
  HotspotTunables,
  IslandsConfig,
  LandmassConfig,
  LandmassGeometry,
  LandmassGeometryPost,
  LandmassTectonicsConfig,
  MountainsConfig,
  OceanSeparationConfig,
  OceanSeparationEdgePolicy,
  PlacementConfig,
  SeaCorridorPolicy,
  StageConfig,
  StageDescriptor,
  StageManifest,
  StartsConfig,
  StoryConfig,
  VolcanoesConfig,
};

export type { ContinentBounds };

export type StageName = string;
