// !! DO NOT EDIT THIS FILE !!
// This file was automatically generated via the metaprogression generation workflow.
// Generator file: Utilities-Metaprogression.stache
// These enums are generated automatically to match with the generated enums in GameCore_MetaprogressionTypes.h

export type ChallengeCategory = number;

export const ChallengeCategorySortIndex: Record<number, number> = {
	0xA50CDA0C: 1000,
	0xA1204F1D: 2000,
	0xF4C0576C: 3000,
	0x9EA05FDB: 4000,
	0xDDA7DA0B: 5000,
	0xE70A8612: 5500,
	0x5B3B86E1: 15000,
	0x25D9F255: 17000,
	0x86BEC1B4: 19000,
	0x6EF2A05C: 20000,
	0x6F55C382: 21000,
	0x7BE7D1D7: 23000,
	0x85F409F6: 24000,
	0x426EB8A6: 25000,
	0x8FAC67C0: 26000,
	0xD4AD682A: 29000,
	0xF48064A3: 30000,
	0x5F0ABED8: 31000,
	0x5DBE3972: 33000,
	0xD5A00487: 34000,
	0xE56DDAC9: 35000,
	0xBF1D1D74: 36000,
	0x8E349162: 38000,
	0xFD5177FD: 41000,
	0x6E2714E5: 43000,
	0x0630AE0D: 44000,
	0xF765915C: 16000,
	0xAE1CED7E: 18000,
	0xFFE78B64: 32000,
	0xC806E8CE: 41500,
	0x969C3310: 27000,
	0xC5555696: 45000,
	0x9520CDF4: 28000,
	0x15DDC641: 37000,
	0xD675AFA1: 39000,
	0xC8F7F388: 40000,
	0xD3C8AC5F: 42000,
}

export enum ChallengeClass {
	CHALLENGE_CLASS_FOUNDATION = 0x0BBFB5F1,
	CHALLENGE_CLASS_LEADER = 0x28327270,
}